### ISSUE TITLE
use dpkg_package with the source attrib, apt_package doesn't work properly

### ISSUE THREAD

**Issue by elijah** [jtimberman/plexapp-cookbook#10]
Hey man,

I gave this cookbook a whirl tonight in a vagrant env, and it blew up on me as follows.

apt_package doesn't seem to support the style of invocation that is in use here - changing from package to dpkg_package makes it Just Work.

best,

--e

> 8>8>8>8>8>8

==> default:
==> default: ================================================================================
==> default: Error executing action `install` on resource 'apt_package[plexmediaserver]'
==> default: ================================================================================
==> default:
==> default:
==> default: Chef::Exceptions::Package
==> default: -------------------------
==> default: apt package provider cannot handle source attribute. Use dpkg provider instead
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-5/chef-solo-1/cookbooks/plexapp/recipes/server.rb
==> default:
==> default:  31: package 'plexmediaserver' do
==> default:  32:   source cached_package_file
==> default:  33: end
==> default:  34:
==> default:

**Comment by tfitch** [comment]
Just encountered the same issue on an Ubuntu 15.04 VM in Vagrant.

**Comment by josephholsten** [comment]
+1
